---
- name: Instalo smartmontools para ver si devices están bien
  ansible.builtin.apt:
    name: smartmontools
    state: present
  register: config_hiperv_install_smartmontools
  until: config_hiperv_install_smartmontools is successful

- name: Verificar estado de los dispositivos
  ansible.builtin.command: "smartctl -H {{ item }}"
  loop: "{{ storage_devices }}"
  register: config_hiperv_disk_status
  changed_when: false
  failed_when: config_hiperv_disk_status.stderr != ""

- name: Desmontar dispositivos
  ansible.posix.mount:
    path: "{{ item }}"
    state: unmounted
  loop: "{{ storage_devices }}"

# Esto elimina particiones, lvm y todo lo que se menee
- name: Eliminar firmas dispositivos
  ansible.builtin.command: "wipefs -af {{ item }}"
  loop: "{{ storage_devices }}"
  register: config_hiperv_delete_fs_status
  failed_when: config_hiperv_delete_fs_status.rc > 0
  changed_when: '"bytes were erased" in config_hiperv_del_fs.stdout'

# Cuando no es posible hacer pvremove debido a metadatos lvm. Los elimino de dmsetup
- name: Verificar config previa como dispositivo ceph
  ansible.builtin.shell: set -o pipefail && lsblk -no NAME {{ item }} | grep -o 'ceph.*'
  args:
    executable: /bin/bash
  loop: "{{ storage_devices }}"
  register: config_hiperv_ceph_lvm_status
  changed_when: false
  failed_when: config_hiperv_ceph_lvm_status.rc != 0 and config_hiperv_ceph_lvm_status.stderr | default('') != ''

- name: Eliminar dispositivo ceph si existe
  ansible.builtin.command: "dmsetup remove {{ item.stdout }}"
  loop: "{{ config_hiperv_ceph_lvm_status.results }}"
  when: item.rc == 0
  register: config_hiperv_delete_lvm_status
  changed_when: config_hiperv_delete_lvm_status.rc != 0

### Posibilidad de meter aquí módulos para crear LVs con los devices recién formateados.
### Pero no se como preguntaría por las variables

# es hacer pvcreate a los vol logicos
# modulo lvg que itere con dos variables: una con nombre del lvg y otra que indique el/los devices a usar
# modulo lvol que itere los vg creados y cree volumen lógico con el 100% de almacenamiento.
