---
- name: Instalo smartmontools para ver si devices están bien
  ansible.builtin.apt:
    name: smartmontools
    state: present
  register: config_hiperv_install_smartmontools
  until: config_hiperv_install_smartmontools is successful

- name: Verificar estado de los dispositivos
  ansible.builtin.command: "smartctl -H {{ item }}"
  loop: "{{ OSD_storage_devices | map('split', ',') | flatten }}"
  register: config_hiperv_disk_status
  changed_when: false
  failed_when: config_hiperv_disk_status.stderr != ""

- name: Desmontar dispositivos
  ansible.posix.mount:
    path: "{{ item }}"
    state: unmounted
  loop: "{{ OSD_storage_devices | map('split', ',') | flatten }}"

# Esto elimina particiones, lvm y todo lo que se menee
- name: Eliminar firmas dispositivos
  ansible.builtin.command: "wipefs -af {{ item }}"
  loop: "{{ OSD_storage_devices | map('split', ',') | flatten }}"
  register: config_hiperv_del_fs
  failed_when: config_hiperv_del_fs.rc > 0
  changed_when: '"bytes were erased" in config_hiperv_del_fs.stdout'

# Cuando no es posible hacer pvremove debido a metadatos lvm. Los elimino de dmsetup
- name: Verificar config previa como dispositivo ceph
  ansible.builtin.shell: set -o pipefail && lsblk -no NAME {{ item }} | grep -o 'ceph.*'
  args:
    executable: /bin/bash
  loop: "{{ OSD_storage_devices | map('split', ',') | flatten }}"
  register: config_hiperv_ceph_lvm_status
  changed_when: false
  failed_when: config_hiperv_ceph_lvm_status.rc != 0 and config_hiperv_ceph_lvm_status.stderr | default('') != ''

- name: Eliminar dispositivo ceph si existe
  ansible.builtin.command: "dmsetup remove {{ item.stdout }}"
  loop: "{{ config_hiperv_ceph_lvm_status.results }}"
  when: item.rc == 0
  register: config_hiperv_delete_lvm_status
  changed_when: config_hiperv_delete_lvm_status.rc != 0

- name: Crear grupo de volumen lógico
  ansible.builtin.lvg:
    vg: "ceph_vg_{{ index }}"
    pvs: "{{ item }}"
    pvresize: true
  loop: "{{ OSD_storage_devices }}"
  loop_control:
    index_var: index

- name: Crear volumen lógico para cada VG
  ansible.builtin.lvol:
    vg: "ceph_vg_{{ index }}"
    lv: "ceph_lv_{{ index }}"
    size: +100%FREE
  loop: "{{ OSD_storage_devices }}"
  loop_control:
    index_var: index
