---
- name: Borrar fingerprints anteriores
  ansible.builtin.known_hosts:
    name: "{{ hostvars[item].ansible_host }}"
    state: absent
  loop: "{{ hostvars.keys() | list }}"

- name: Obtener fingerprints de hosts
  ansible.builtin.command: "ssh-keyscan {{ hostvars[item].ansible_host }}"
  register: fingerprints
  changed_when: fingerprints.rc != 0
  loop: "{{ hostvars.keys() | list }}"

- name: Registrar fingerprints en ~/.ssh/known_hosts
  ansible.builtin.known_hosts:
    name: "{{ hostvars[item.item].ansible_host }}"
    key: "{{ item.stdout }}"
    state: present
  loop: "{{ fingerprints.results }}"
