---
- name: Añadir clave gpg de grafana
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key
    mode: '644'
    force: true # Actualizar siempre

- name: Añado repositorio oficial grafana
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main"
    state: present
    filename: grafana

- name: Instalar grafana
  ansible.builtin.apt:
    name: grafana-enterprise
    state: present
    update_cache: true
  register: monitoring_grafana_installed
  until: monitoring_grafana_installed is successful

- name: Fichero grafana.ini
  ansible.builtin.copy:
    src: files/grafana.ini
    dest: /etc/grafana/grafana.ini
    mode: '640'
    group: grafana

- name: Añadir plugins usados por algunos dashboards
  community.grafana.grafana_plugin:
    name: "{{ item }}"
    version: latest
    state: present
  loop:
    - vonage-status-panel
    - grafana-piechart-panel

### A partir de aquí puedo o usar los modulos ansible de grafana para añadir los recursos atacando la url
### O poblar grafana con ficheros "providers" tal y como hacía en la configuración manual.
### Lo hago con la primera opción

- name: Arrancar grafana
  ansible.builtin.systemd:
    name: grafana-server.service
    state: started
    enabled: true

- name: Añadir Datasource Prometheus
  community.grafana.grafana_datasource:
    name: Dashboard1
    ds_type: prometheus
    ds_url: http://localhost:9090
    access: proxy
    is_default: true
    grafana_url: http://localhost:3000/
    org_id: 1
    tls_skip_verify: true

- name: Buscar dashboards de OpenNebula descargados
  ansible.builtin.find:
    paths: /usr/share/one/grafana/dashboards/
    file_type: file
  register: monitoring_opennebula_dashboards

- name: Crear directorios para los Dashboards en Grafana
  community.grafana.grafana_folder:
    url: http://localhost:3000/
    title: "{{ item }}"
    state: present
  loop:
    - "OpenNebula Dashboards"
    - "Ceph Dashboards"
    - "Node Exporters"

- name: Importar Dashboards de OpenNebula
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000/
    org_id: 1
    commit_message: Dashboards de OpenNebula
    folder: OpenNebula Dashboards
    path: "{{ item }}"
    overwrite: true
  loop: "{{ monitoring_opennebula_dashboards.files | map(attribute='path') | list }}"


- name: Obtener lista de Dashboards de Ceph del repositorio oficial
  ansible.builtin.uri:
    url: "https://api.github.com/repos/ceph/ceph/contents/monitoring/ceph-mixin/dashboards_out"
    method: GET
    return_content: true
    headers:
      Accept: "application/vnd.github.v3+json"
  register: monitoring_ceph_dashboards

- name: Importar Dashboards de Ceph
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000/
    org_id: 1
    commit_message: Dashboards Oficiales de Ceph
    folder: Ceph Dashboards
    path: "https://raw.githubusercontent.com/ceph/ceph/main/monitoring/ceph-mixin/dashboards_out/{{ item }}"
    overwrite: true
  loop: "{{ monitoring_ceph_dashboards.json |
            selectattr('type', 'equalto', 'file') |
            map(attribute='name') |
            select('match', '.*\\.json$') | list }}"
  when: item != "ceph-cluster.json"

- name: Importar Dashboard de Ceph Overview
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000/
    org_id: 1
    commit_message: Ceph-Overview
    folder: Ceph Dashboards
    dashboard_id: 2842
    dashboard_revision: 16
    overwrite: true

- name: Importar Dashboard para los Node Exporters
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000/
    org_id: 1
    commit_message: Dashboard para los Node Exporters
    folder: Node Exporters
    path: "https://raw.githubusercontent.com/rfmoz/grafana-dashboards/master/prometheus/node-exporter-full.json"
    overwrite: true
