---
- name: Instalar opennebula-node-kvm
  ansible.builtin.apt:
    name: opennebula-node-kvm # opennebula-node-kvm=6.6.0-1
    state: present
  register: opennebula_kvm_install_result
  until: opennebula_kvm_install_result is successful
  notify:
    - Restart Libvirt
    - Apt Autoremove

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
