---
- name: Agregar clave pública de oneadmin al resto de hosts
  ansible.posix.authorized_key:
    user: oneadmin
    state: present
    key: "{{ lookup('pipe', 'ssh root@' ~ groups['frontend'][0] ~ ' cat /var/lib/one/.ssh/id_rsa.pub') }}"
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups['hipervisores'] }}"
