---
- name: Borro anteriores ficheros known_hosts ya que idempotencia falla al actualizar ficheros previos
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /root/.ssh/known_hosts
    - /var/lib/one/.ssh/known_hosts

- name: Creo fichero known_hosts
  ansible.builtin.known_hosts:
    path: /root/.ssh/known_hosts
    name: "{{ hostvars[item.0].ansible_host }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -t {{ item.1 }} {{ hostvars[item.0].ansible_host }}', errors='ignore') | default('') }}"
    state: present
  with_nested:
    - "{{ groups['all'] }}"
    - "{{ public_keys }}"
  ignore_errors: true # Lookup da error si no encuentra una clave, en este caso no suele encontrar la de ssh-dss
  # Me va a salir warning siempre que no defina que los errores ignorables sólo sean los del lookup.
  # Conseguir eso me llevaría demasiado tiempo.


