---
- name: "Sudo sin contraseña para {{ ansible_user }}"
  ansible.builtin.copy:
    content: "%{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/{{ ansible_user }}
    mode: '644' # 0440 también vale
    validate: visudo -cf %s

- name: "Ssh root permitido"
  ansible.builtin.copy:
    content: |
      PermitRootLogin {{ permitrootlogin }}
      PasswordAuthentication {{ passwordauthentication }}
    dest: /etc/ssh/sshd_config.d/ansible_sshd.config
    mode: '644' # 0440 también vale
  notify: Reiniciar sshd

- name: Ssh labuser sin contraseña desde esta máquina
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

- name: Ssh root sin contraseña desde esta máquina
  ansible.posix.authorized_key:
    user: "root"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
