---
### Ruta http "insegura"
global:
  http_config:
    tls_config:
      insecure_skip_verify: true

route:
  receiver: 'web.hook'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'

### Para mutear alarmas si hay otras activas. En principio no silencio nada
# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']
