---
- name: Instalar MySQL
  ansible.builtin.apt:
    pkg:
      - mysql-server
      - mysql-client    # dudo de que este sea necesario del todo
      - libmysqlclient-dev
    update_cache: true
  register: config_frontend_downloaded_mysql
  until: config_frontend_downloaded_mysql is successful

- name: MySQL activo y enabled
  ansible.builtin.systemd:
    name: mysql
    state: started
    enabled: true

### Para usar ansible en mysql necesito un módulo de python que solo puede ser instalado con pip
- name: Instalar python3-pip
  ansible.builtin.apt:
    name: python3-pip
    update_cache: true

- name: Instalar paquete de python mysqlclient
  ansible.builtin.pip:
    name: mysqlclient

### Pasos que se supone que son como los de "mysql_secure_instalation"
### En principio mantengo el root sin contraseña

# - name: Cambiar contraseña de root
#   mysql_user:
#     name: root
#     password: nueva_contraseña
#     update_password: always

# - name: Eliminar usuarios anónimos de todos los hosts
#   mysql_user:
#     name: ''
#     host_all: true
#     state: absent

# - name: Eliminar acceso remoto de root
#   mysql_user:
#     name: root
#     host: "{{ item }}"
#     state: absent
#   loop:
#     - ::1
#     - 127.0.0.1
#     - "{{ ansible_default_ipv4.address }}"

# - name: Eliminar base de datos de prueba
#   mysql_db:
#     name: test
#     state: absent

# - name: Reiniciar servicio de MySQL
#   service:
#     name: mysql
#     state: restarted
