---
### devices.yml
config_devices: false

### docker.yml
install_docker: true
docker_dependencies:
  - gnupg
  - wget
  - apt-transport-https
  - ca-certificates
  - curl
  - lsb-release
  - software-properties-common
  - gnupg-agent
docker_repo: https://download.docker.com/linux/ubuntu

### iptables.yml
config_iptables: false
