---
- name: Activo servicios de exporters
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - opennebula-exporter.service
    - opennebula-node-exporter.service
    - opennebula-libvirt-exporter.service
  listen: Reiniciar one-exporters

- name: Reiniciar y habilitar prometheus
  ansible.builtin.systemd:
    name: opennebula-prometheus.service
    state: restarted
    enabled: true
  listen: Reiniciar prometheus

- name: Reiniciar y habilitar alertmanager
  ansible.builtin.systemd:
    name: opennebula-alertmanager.service
    state: restarted
    enabled: true
    daemon_reload: true
  listen: Reiniciar alertmanager
